version: "3.7"
services:
  web-server:
    container_name: cushib-dev-web-server
    build:
      dockerfile: ./docker/ubuntu.Dockerfile
      context: .
    # restart: always
    volumes:
      - "./web:/var/www/html/"
    ports:
      - "8080:80"
      - "443:443"
    tty: true
